### ISSUE TITLE
Launch params should be documented in README

### ISSUE THREAD

**Issue by t0ff3r** [ianwalter/puppeteer#27]
First of all thanks for creating this action :-)

I had some issues for a while but discovered a critical piece of information in your Dockerfile. This should probably be documented in the README.md

```
# Puppeteer will need to be launched with:
#   browser.launch({ executablePath: 'google-chrome-unstable' })
```

**Comment by ianwalter** [comment]
PR welcome otherwise I'll have to get to it later.
